#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '{build}'

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

configuration: Release

platform: Any CPU

environment:
  package_version: '1.0.1'

nuget:
  project_feed: true
  disable_publish_on_pr: true

init:
- ps: |
    git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(RELEASE_VERSION)'
  package_version: '$(PACKAGE_VERSION)'

hosts:
  redis: 127.0.0.1

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
- ps: |
    # install Redis
    choco install redis-64
    redis-server --service-install

    # versioning
    $branch = @{ $true = $env:APPVEYOR_REPO_BRANCH; $false = $(git symbolic-ref --short -q HEAD) }[$env:APPVEYOR_REPO_BRANCH -ne $NULL];
    $revision = @{ $true = "{0:00000}" -f [convert]::ToInt32("0" + $env:APPVEYOR_BUILD_NUMBER, 10); $false = "local" }[$env:APPVEYOR_BUILD_NUMBER -ne $NULL];
    $suffix = @{ $true = ""; $false = "$($branch.Substring(0, [math]::Min(10,$branch.Length)))-$revision"}[$branch -eq "master" -and $revision -ne "local"]
    $env:RELEASE_VERSION_SUFFIX = @{ $true = "--version-suffix $($suffix)"; $false = ""}[$suffix -ne ""]
    $env:RELEASE_VERSION = @{ $true = "$env:PACKAGE_VERSION.$($suffix)"; $false = "$env:PACKAGE_VERSION"}[$suffix -ne ""]

    echo "Version is $env:RELEASE_VERSION"
    echo "Version suffix is $env:RELEASE_VERSION_SUFFIX" 

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
- ps: |
    dotnet restore -v Minimal

build_script:
- ps: |
    dotnet build "src\AspNetCore.CongestionControl" -c $env:CONFIGURATION --no-dependencies --no-restore $env:RELEASE_VERSION_SUFFIX -v Minimal
    dotnet build "test\AspNetCore.CongestionControl.UnitTests" -c $env:CONFIGURATION --no-dependencies --no-restore $env:RELEASE_VERSION_SUFFIX -v Minimal
    dotnet build "test\AspNetCore.CongestionControl.IntegrationTests" -c $env:CONFIGURATION --no-restore $env:RELEASE_VERSION_SUFFIX -v Minimal

after_build:
- ps: |
    dotnet pack "src\AspNetCore.CongestionControl" -c $env:CONFIGURATION --no-build --include-symbols -o artifacts -v Minimal

#---------------------------------#
#       tests configuration       # 
#---------------------------------#

before_test:
- ps: |
    redis-server --service-start

test_script:
- ps: |
    dotnet test "test\AspNetCore.CongestionControl.UnitTests\AspNetCore.CongestionControl.UnitTests.csproj" -c $env:CONFIGURATION --no-build -v Minimal
    dotnet test "test\AspNetCore.CongestionControl.IntegrationTests\AspNetCore.CongestionControl.IntegrationTests.csproj" -c $env:CONFIGURATION --no-build -v Minimal

after_test:
- ps: |
    redis-server --service-stop
    redis-server --service-uninstall

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: src\AspNetCore.CongestionControl\artifacts\**\*.*
  name: NuGet

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: NuGet
    name: Production
    api_key:
      secure: ZyNMTHl83Q+jbtyCaweu6ULT7jo2dGq+lF7TibDcVyE1aH9KKvdmf9FEHkRQHVCL
    on:
      appveyor_repo_tag: true 