name: build

on:
  push:
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

env:
  # Project paths
  PROJECT_PATH: "./src/AspNetCore.CongestionControl/AspNetCore.CongestionControl.csproj"
  UNIT_TEST_PROJECT_PATH: "./test/AspNetCore.CongestionControl.UnitTests/AspNetCore.CongestionControl.UnitTests.csproj"
  INTEGRATION_TEST_PROJECT_PATH: "./test/AspNetCore.CongestionControl.IntegrationTests/AspNetCore.CongestionControl.IntegrationTests.csproj"

  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET on CI runner
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

  build:
    needs: prepare
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Unit Test
      run: dotnet test $UNIT_TEST_PROJECT_PATH -c Release --no-build

    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0

    - name: Integration Test
      run: dotnet test $INTEGRATION_TEST_PROJECT_PATH -c Release --no-build

    - name: Version
      id: version
      uses: hennejg/github-tag-action@v4.2.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Package
      if: github.event_name == 'release'
      run: dotnet pack -v normal -c Release -o nupkg --no-restore --include-symbols --include-source -p:PackageVersion=${{ steps.version.outputs.new_version }} $PROJECT_PATH

    - name: Upload Artifact
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./nupkg/*.nupkg

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: nupkg
          path: ./nupkg

      - name: Push to NuGet Feed
        run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
