name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest    

    steps:
    - name: Setup .NET on CI runner
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

  build:
    needs: prepare
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      env:
        PROJECT_PATH: "./src/AspNetCore.CongestionControl/AspNetCore.CongestionControl.csproj"
      run: dotnet build $PROJECT_PATH --configuration Release

    - name: Unit Test
      env:
        PROJECT_PATH: "./test/AspNetCore.CongestionControl.UnitTests/AspNetCore.CongestionControl.UnitTests.csproj"
      run: dotnet test $PROJECT_PATH

    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0

    - name: Integration Test
      env:
        PROJECT_PATH: "./test/AspNetCore.CongestionControl.IntegrationTests/AspNetCore.CongestionControl.IntegrationTests.csproj"
      run: dotnet test $PROJECT_PATH

    - name: Version
      id: version
      uses: hennejg/github-tag-action@v4.2.4
      with:
        release_branches: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: "true"

    - name: Package
      env:
        PROJECT_PATH: "./src/AspNetCore.CongestionControl/AspNetCore.CongestionControl.csproj"
      run: dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=${{ steps.version.outputs.new_version }} $PROJECT_PATH
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./src/AspNetCore.CongestionControl/bin/Release/*.nupkg
  
